// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: serviceId.proto

package serviceId

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// serviceID 段的标志，进行路由用
type ID int32

const (
	ID_LOGIN    ID = 16 // 登录服
	ID_CHAT     ID = 17 // 聊天服
	ID_USER     ID = 18 // 用户服(用户请求一些关于个人信息，或者修改信息)
	ID_TABLE    ID = 19 // 桌子服(用户进行比配以及进行比赛时，请求该服务)
	ID_MATCH    ID = 20 // 比赛服
	ID_REGISTRY ID = 21 // 注册服
)

// Enum value maps for ID.
var (
	ID_name = map[int32]string{
		16: "LOGIN",
		17: "CHAT",
		18: "USER",
		19: "TABLE",
		20: "MATCH",
		21: "REGISTRY",
	}
	ID_value = map[string]int32{
		"LOGIN":    16,
		"CHAT":     17,
		"USER":     18,
		"TABLE":    19,
		"MATCH":    20,
		"REGISTRY": 21,
	}
)

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID) Descriptor() protoreflect.EnumDescriptor {
	return file_serviceId_proto_enumTypes[0].Descriptor()
}

func (ID) Type() protoreflect.EnumType {
	return &file_serviceId_proto_enumTypes[0]
}

func (x ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ID(num)
	return nil
}

// Deprecated: Use ID.Descriptor instead.
func (ID) EnumDescriptor() ([]byte, []int) {
	return file_serviceId_proto_rawDescGZIP(), []int{0}
}

var File_serviceId_proto protoreflect.FileDescriptor

var file_serviceId_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x2a, 0x47, 0x0a, 0x02,
	0x49, 0x44, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x10, 0x12, 0x08, 0x0a,
	0x04, 0x43, 0x48, 0x41, 0x54, 0x10, 0x11, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10,
	0x12, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x13, 0x12, 0x09, 0x0a, 0x05,
	0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x14, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x47, 0x49, 0x53,
	0x54, 0x52, 0x59, 0x10, 0x15,
}

var (
	file_serviceId_proto_rawDescOnce sync.Once
	file_serviceId_proto_rawDescData = file_serviceId_proto_rawDesc
)

func file_serviceId_proto_rawDescGZIP() []byte {
	file_serviceId_proto_rawDescOnce.Do(func() {
		file_serviceId_proto_rawDescData = protoimpl.X.CompressGZIP(file_serviceId_proto_rawDescData)
	})
	return file_serviceId_proto_rawDescData
}

var file_serviceId_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_serviceId_proto_goTypes = []interface{}{
	(ID)(0), // 0: serviceId.ID
}
var file_serviceId_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serviceId_proto_init() }
func file_serviceId_proto_init() {
	if File_serviceId_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serviceId_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serviceId_proto_goTypes,
		DependencyIndexes: file_serviceId_proto_depIdxs,
		EnumInfos:         file_serviceId_proto_enumTypes,
	}.Build()
	File_serviceId_proto = out.File
	file_serviceId_proto_rawDesc = nil
	file_serviceId_proto_goTypes = nil
	file_serviceId_proto_depIdxs = nil
}
